[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dcd"
version = "0.0.1"
authors = [
    {name = "Phuc Phan", email = "phanphuc1100@gmail.com"},
]
requires-python = ">=3.8"
dependencies = [
    "transformers",
    "accelerate"
]